
<table>
{
   $OUT .= qq{
      <thead>
          <th style="background-color: #d3d3d3;"> <strong> rowid </strong> </th>
          <th> md5 </th>
          <th> img</th>
          <th> remote</th>
          <th> url_md5 </th>
          <th> url </th>
      </thead>
   };
   $OUT .= '<tbody>';
   for my $row (@rows){
     $OUT .= '<tr>';
     my ($rowid, $inum, $url, $url_md5, $md5, $img) = @{$row}{qw( rowid inum url url_md5 md5 img )};
     my $url_img = qq{/img/raw/$inum};
     $url =~ s/strana\.ua/strana.news/g;
     $OUT .= qq{
        <td style="background-color: #d3d3d3;"> <strong> $rowid </strong> </td>
        <td> $md5 </td>
        <td> <a href="$url_img" target="_blank">$img</a></td>
        <td> <a href="$url" target="_blank">remote</a></td>
        <td>$url_md5</td>
        <td>$url</td>
     };
     $OUT .= '</tr>';
   }
   $OUT .= '</tbody>';
}
</table>
